# Generated by Django 6.1.1 on 2026-09-15 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_title_min_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
