# Generated by Django 6.1.1 on 2026-09-15 14:03

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_unique_category_name_per_parent'),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='catalog_product_title_trgm'),
        ),
    ]
